In [1]:
from keras.models import load_model
new_model1 = load_model("cnn_10epochsO.model")
new_model2 = load_model("cnn_10epochsC.model")
new_model3 = load_model("cnn_10epochsE.model")
new_model4 = load_model("cnn_10epochsA.model")
new_model5 = load_model("cnn_10epochsN.model")


Using TensorFlow backend.


In [2]:
from keras.optimizers import RMSprop
opt = RMSprop(lr=0.001, rho=0.9, epsilon=None)

new_model1.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model2.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model3.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model4.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model5.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])

In [3]:
import pickle
import numpy as np


In [4]:
def get_idx_from_sent(sent, word_idx_map, max_l=51, kernel_size=5):
    """
    Transforms sentence into a list of indices. Pad with zeroes.
    """
    x = []
    pad = kernel_size - 1
    for i in range(pad):
        x.append(0)
    words = sent.split()
    for word in words:
        if word in word_idx_map:
            x.append(word_idx_map[word])
    while len(x) < max_l+2*pad:
        x.append(0)
    return x

def make_idx_data(revs, word_idx_map, max_l=51, kernel_size=5):
    """
    Transforms sentences into a 2-d matrix.
    """
    test = []
    for rev in revs:
        sent = get_idx_from_sent(rev['text'], word_idx_map, max_l, kernel_size)
        sent.append(rev['y'])
        test.append(sent)
    test = np.array(test, dtype=np.int)
    return test


print ("loading data...")
with open("imdb-test.pickle", 'rb') as f:
    x = pickle.load(f, encoding='latin')
revs, W, word_idx_map, vocab = x[0], x[1], x[2], x[3]
print ("data loaded!")


datasets = make_idx_data(revs, word_idx_map,max_l = 2721,kernel_size=5)
print(datasets)

loading data...
data loaded!
[[ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0 -1]
 ...
 [ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0 -1]]


In [10]:
Nt = datasets.shape[0]
test_X = np.zeros((Nt,2729), dtype=np.int)
for i in range(Nt):
    for j in range(2729):
       test_X[i, j] = datasets[i, j]
    
print ('test_X.shape = {}'.format(test_X.shape))


test_X.shape = (468, 2729)


In [11]:
test_X[0][543]

13093

In [12]:
o = new_model1.predict(test_X, verbose = 1)


468/468 [==============================] - 9s 19ms/step


In [16]:
o.shape

(468, 2)

In [22]:
for i in range(o.shape[0]):
    o[i][0] = int(o[i][0]>0.5)
    o[i][1] = int(o[i][1]>0.5)    

In [33]:
print(n)

[[0.45483884 0.5451612 ]
 [0.45176074 0.5482392 ]
 [0.4514945  0.5485055 ]
 [0.45379716 0.54620284]
 [0.45522684 0.54477316]
 [0.45554453 0.5444555 ]
 [0.45304406 0.5469559 ]
 [0.45181745 0.54818255]
 [0.45393234 0.54606766]
 [0.45384136 0.54615855]
 [0.45277917 0.5472208 ]
 [0.4548822  0.54511786]
 [0.4531768  0.5468232 ]
 [0.45183384 0.5481661 ]
 [0.4542686  0.54573137]
 [0.4507849  0.54921514]
 [0.45305702 0.54694295]
 [0.4524046  0.5475954 ]
 [0.4518067  0.5481933 ]
 [0.45476517 0.54523486]
 [0.45450994 0.5454901 ]
 [0.4534671  0.54653287]
 [0.45426136 0.54573864]
 [0.45207188 0.54792815]
 [0.45497724 0.5450227 ]
 [0.44912016 0.5508798 ]
 [0.4546608  0.54533917]
 [0.45328316 0.54671687]
 [0.45440927 0.5455907 ]
 [0.45396417 0.5460359 ]
 [0.45307365 0.5469263 ]
 [0.45365074 0.5463492 ]
 [0.45551574 0.54448426]
 [0.4540659  0.54593414]
 [0.4528858  0.54711413]
 [0.4566949  0.5433051 ]
 [0.454849   0.54515094]
 [0.4526771  0.5473229 ]
 [0.44940734 0.55059266]
 [0.4546925  0.5453075 ]


In [24]:
c = new_model2.predict(test_X, verbose = 1)


468/468 [==============================] - 1s 2ms/step


In [25]:
e = new_model3.predict(test_X, verbose = 1)


468/468 [==============================] - 1s 2ms/step


In [26]:
a = new_model4.predict(test_X, verbose = 1)


468/468 [==============================] - 1s 2ms/step


In [31]:
n = new_model5.predict(test_X, verbose = 1)

468/468 [==============================] - 1s 2ms/step


In [32]:
print(n)

[[0.45483884 0.5451612 ]
 [0.45176074 0.5482392 ]
 [0.4514945  0.5485055 ]
 [0.45379716 0.54620284]
 [0.45522684 0.54477316]
 [0.45554453 0.5444555 ]
 [0.45304406 0.5469559 ]
 [0.45181745 0.54818255]
 [0.45393234 0.54606766]
 [0.45384136 0.54615855]
 [0.45277917 0.5472208 ]
 [0.4548822  0.54511786]
 [0.4531768  0.5468232 ]
 [0.45183384 0.5481661 ]
 [0.4542686  0.54573137]
 [0.4507849  0.54921514]
 [0.45305702 0.54694295]
 [0.4524046  0.5475954 ]
 [0.4518067  0.5481933 ]
 [0.45476517 0.54523486]
 [0.45450994 0.5454901 ]
 [0.4534671  0.54653287]
 [0.45426136 0.54573864]
 [0.45207188 0.54792815]
 [0.45497724 0.5450227 ]
 [0.44912016 0.5508798 ]
 [0.4546608  0.54533917]
 [0.45328316 0.54671687]
 [0.45440927 0.5455907 ]
 [0.45396417 0.5460359 ]
 [0.45307365 0.5469263 ]
 [0.45365074 0.5463492 ]
 [0.45551574 0.54448426]
 [0.4540659  0.54593414]
 [0.4528858  0.54711413]
 [0.4566949  0.5433051 ]
 [0.454849   0.54515094]
 [0.4526771  0.5473229 ]
 [0.44940734 0.55059266]
 [0.4546925  0.5453075 ]


In [28]:
for i in range(468):
    o[i][0] = int(o[i][0]>0.5)
    o[i][1] = int(o[i][1]>0.5)
    c[i][0] = int(c[i][0]>0.5)
    c[i][1] = int(c[i][1]>0.5)
    e[i][0] = int(e[i][0]>0.5)
    e[i][1] = int(e[i][1]>0.5)
    a[i][0] = int(a[i][0]>0.5)
    a[i][1] = int(a[i][1]>0.5)
    n[i][0] = int(n[i][0]>0.5)
    n[i][1] = int(n[i][1]>0.5) 

In [30]:

print(c)
print(e)
print(a)
print(n)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 

In [30]:
dict = {}
tr = 'ocean'
for i in range(5):
    for row in p[i]:
        r = row[1] 
        r *= 10000000
        r = r % 100
        r = int(r)
        r = int(r > 50)
        dict[tr[i]] = r
print(dict)            
        

{'o': 0, 'c': 0, 'e': 1, 'a': 1, 'n': 1}
