In [1]:
from keras.models import load_model
new_model1 = load_model("cnn_10epochsO.model")
new_model2 = load_model("cnn_10epochsC.model")
new_model3 = load_model("cnn_10epochsE.model")
new_model4 = load_model("cnn_10epochsA.model")
new_model5 = load_model("cnn_10epochsN.model")


Using TensorFlow backend.


In [2]:
from keras.optimizers import RMSprop
opt = RMSprop(lr=0.001, rho=0.9, epsilon=None)

new_model1.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model2.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model3.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model4.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model5.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])

In [3]:
import pickle
import numpy as np


In [4]:
def get_idx_from_sent(sent, word_idx_map, max_l=51, kernel_size=5):
    """
    Transforms sentence into a list of indices. Pad with zeroes.
    """
    x = []
    pad = kernel_size - 1
    for i in range(pad):
        x.append(0)
    words = sent.split()
    for word in words:
        if word in word_idx_map:
            x.append(word_idx_map[word])
    while len(x) < max_l+2*pad:
        x.append(0)
    return x

def make_idx_data(revs, word_idx_map, max_l=51, kernel_size=5):
    """
    Transforms sentences into a 2-d matrix.
    """
    test = []
    for rev in revs:
        sent = get_idx_from_sent(rev['text'], word_idx_map, max_l, kernel_size)
        sent.append(rev['y'])
        test.append(sent)
    test = np.array(test, dtype=np.int)
    return test


print ("loading data...")
with open("imdb-test.pickle", 'rb') as f:
    x = pickle.load(f, encoding='latin')
revs, W, word_idx_map, vocab = x[0], x[1], x[2], x[3]
print ("data loaded!")


datasets = make_idx_data(revs, word_idx_map,max_l = 2721,kernel_size=5)
print(datasets)

loading data...
data loaded!
[[ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0 -1]
 ...
 [ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0 -1]
 [ 0  0  0 ...  0  0 -1]]


In [10]:
Nt = datasets.shape[0]
test_X = np.zeros((Nt,2729), dtype=np.int)
for i in range(Nt):
    for j in range(2729):
       test_X[i, j] = datasets[i, j]
    
print ('test_X.shape = {}'.format(test_X.shape))


test_X.shape = (468, 2729)


In [11]:
test_X[0][543]

13093

In [12]:
o = new_model1.predict(test_X, verbose = 1)


468/468 [==============================] - 9s 19ms/step


In [16]:
o.shape

(468, 2)

In [22]:
for i in range(o.shape[0]):
    o[i][0] = o[i][0]>0.5
    o[i][1] = o[i][1]>0.5    

In [24]:
c = new_model2.predict(test_X, verbose = 1)


468/468 [==============================] - 1s 2ms/step


In [25]:
e = new_model3.predict(test_X, verbose = 1)


468/468 [==============================] - 1s 2ms/step


In [26]:
a = new_model4.predict(test_X, verbose = 1)


468/468 [==============================] - 1s 2ms/step


In [31]:
n = new_model5.predict(test_X, verbose = 1)

468/468 [==============================] - 1s 2ms/step


In [28]:
for i in range(468):
    o[i][0] = int(o[i][0]>0.5)
    o[i][1] = int(o[i][1]>0.5)
    c[i][0] = int(c[i][0]>0.5)
    c[i][1] = int(c[i][1]>0.5)
    e[i][0] = int(e[i][0]>0.5)
    e[i][1] = int(e[i][1]>0.5)
    a[i][0] = int(a[i][0]>0.5)
    a[i][1] = int(a[i][1]>0.5)
    n[i][0] = int(n[i][0]>0.5)
    n[i][1] = int(n[i][1]>0.5) 